### ISSUE TITLE
error when running worklflow

### ISSUE THREAD

**Issue by ryandeussing** [dlbewley/alfred-rh411#1]
Firstly, thanks for sharing this! 

Here is the error I'm getting. Am I misunderstanding the query syntax? 

![x](https://p45.f4.n0.cdn.getcloudapp.com/items/xQubP8g9/cbb57e34-61a2-4bea-a68f-9d7ec9372ebb.gif?source=viewer&v=4b9e771742ed47f46e7f00e908117009)

**Comment by dlbewley** [comment]
I'm happy to learn someone else is interested!

The query syntax is pretty limited. It will search **last** names and usernames basically. It looks like there is something broken.

What version of Alfred are you running? At least v3 is required.

Please go into Alfred preferences, click on the rh411 workflow, then click the bug icon in the top right corner to enable debugging. Then try again and send me the log output, so we can investigate that Python syntax error.

Also, you might try v0.0.11 of the workflow.

Feel free to hit me up on Google Chat.

**Comment by ryandeussing** [comment]
Pasting here for the syntax highlighting:

```python
[22:37:01.318] Red Hat 411[Script Filter] Queuing argument 'rdeussin'
[22:37:02.293] Red Hat 411[Script Filter] Script with argv '(null)' finished
[22:37:02.297] ERROR: Red Hat 411[Script Filter] Code 1: 22:37:02 workflow.py:1695 DEBUG    loading cached data: /Users/ryandeussing/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/net.bewley.dale.rh411/__workflow_latest_version.cpickle
.
22:37:02 workflow.py:2061 DEBUG    ---------- Red Hat 411 (0.0.11) ----------
22:37:02 workflow.py:1468 DEBUG    reading settings from /Users/ryandeussing/Library/Application Support/Alfred/Workflow Data/net.bewley.dale.rh411/settings.json
22:37:02 workflow.py:2343 DEBUG    update check not due
22:37:02 workflow.py:2080 ERROR    invalid syntax (__init__.py, line 1367)
Traceback (most recent call last):
  File "/Users/ryandeussing/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.99D8C48D-A5DE-4B6A-8358-5D2ACBCC7AE5/workflow/workflow.py", line 2073, in run
    func(self)
  File "ldap-alfred.py", line 52, in main
    import humanize
  File "./lib/humanize/__init__.py", line 2, in <module>
    import pkg_resources
  File "./lib/pkg_resources/__init__.py", line 1367
    raise SyntaxError(e) from e
                            ^
SyntaxError: invalid syntax
22:37:02 workflow.py:2103 DEBUG    ---------- finished in 0.046s ----------
[22:37:02.300] Red Hat 411[Script Filter] {
  "items": [
    {
      "valid": false,
      "subtitle": "invalid syntax (__init__.py, line 1367)",
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
      },
      "title": "Error in workflow 'Red Hat 411'"
    }
  ]
}
```

**Comment by ryandeussing** [comment]
the above is v0.0.11

**Comment by dlbewley** [comment]
I made a couple of changes to ensure python2 compatibility, which is required for Alfred. 

Please try v0.0.13a when you have a chanc.

**Comment by ryandeussing** [comment]
All set,
